import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { Toaster } from "@/components/ui/toaster";

// Dynamically import components that aren't needed for initial render
const Header = dynamic(() => import("@/components/Header"), {
  ssr: true
});
const Footer = dynamic(() => import("@/components/Footer"), {
  ssr: true
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weights: [400, 500, 700],
  variable: '--font-jetbrainsMono',
  display: 'swap',
});

export const metadata = {
    title: "Efosa Igbinehi | AI Software Engineer",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
      <Header />
        {children}
      <Footer />
      <Toaster />
      </body>
    </html>
  );
}
