import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

// Dynamically import components that aren't needed for initial render
const Header = dynamic(() => import("@/components/Header"), {
  ssr: true // Keep true if header is needed for SEO
});
const Footer = dynamic(() => import("@/components/Footer"), {
  ssr: true
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  // Optimize font loading by only including weights you actually use
  weights: [400, 500, 700], // Reduce number of weights
  variable: '--font-jetbrainsMono',
  display: 'swap', // Add display swap for better performance
});

export const metadata = {
    title: "Efosa Igbinehi | AI Software Engineer",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
